### ISSUE TITLE
Catkin make error

### ISSUE THREAD

**Issue by yoggi56** [loco-3d/whole_body_state_rviz_plugin#24]
Hello!
I'm trying to build your project but have an errors during catkin_make. 
My system is Ubuntu 20.04, ROS Noetic with installed Pinocchio using robotpkg.

The error:
/usr/include/OGRE/OgreAxisAlignedBox.h:722:21: error: implicitly-declared ‘constexpr Ogre::Vector3::Vector3(const Ogre::Vector3&)’ is deprecated [-Werror=deprecated-copy]
  722 |     return Vector3::ZERO;
      |                     ^~~~
In file included from /usr/include/OGRE/OgreMatrix3.h:33,
                 from /usr/include/OGRE/OgreNode.h:34,
                 from /usr/include/OGRE/OgreSceneNode.h:33,
                 from /usr/include/OGRE/OgreSceneManager.h:37,
                 from /home/yoggi/ros_ws/src/whole_body_state_rviz_plugin/src/PolygonVisual.cpp:9:
/usr/include/OGRE/OgreVector3.h:134:25: note: because ‘Ogre::Vector3’ has user-provided ‘Ogre::Vector3& Ogre::Vector3::operator=(const Ogre::Vector3&)’
  134 |         inline Vector3& operator = ( const Vector3& rkVector )
      |                         ^~~~~~~~
In file included from /usr/include/OGRE/OgreMesh.h:35,
                 from /usr/include/OGRE/OgreNode.h:40,
                 from /usr/include/OGRE/OgreSceneNode.h:33,
                 from /usr/include/OGRE/OgreSceneManager.h:37,
                 from /home/yoggi/ros_ws/src/whole_body_state_rviz_plugin/src/PolygonVisual.cpp:9:

**Comment by cmastalli** [comment]
Hi @yoggi56!

I am not sure why you are encountering this issue as our CI is testing Noetic.

Could you report your Pinocchio version? Could you install Pinocchio via ROS?

**Comment by yoggi56** [comment]
Installed Pinocchio via ROS:
`sudo apt install ros-noetic-pinocchio`
But I still encounter the same problem during `catkin_make`
Pinocchio version: 2.6.17-1focal.20230317.180406
Python version: Python 3.8.10

**Comment by wxmerkt** [comment]
What is your catkin workspace config? I don't think we set the `-Werror` flag in our projects - and that's what you are seeing; warnings treated as errors. It passes the build on the buildserver so is likely an issue on your system/workspace setup.

**Comment by yoggi56** [comment]
Using `set(CMAKE_CXX_FLAGS "-std=c++14 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-copy -Wno-unused-but-set-parameter" CACHE STRING "" FORCE)` in `CMakeList.txt` file helped me. Thank you for your help!
