### ISSUE TITLE
Reemc wrong model

### ISSUE THREAD

**Issue by NigerChel** [loco-3d/whole_body_state_rviz_plugin#4]
Hi WBS rviz-plugin developers,

First, I want to thank for your plugin. I would like to make an example documentation for Reemc; but unfortunately, when I add the plugin in rviz, it shows a wrong piece of the model instead of the right model of Reemc. 

![reemc_plugin1](https://user-images.githubusercontent.com/66029337/101414050-0175ea00-38ab-11eb-9385-81d02958e568.png)

Is there a way how to fix this?

Any answer will be helpful.

Thanks in advance!

**Comment by cmastalli** [comment]
You need to subscribe to a topic that publishes the whole-body state message.

I suggest you to start with a Python script that publishes such kind of message

**Comment by cmastalli** [comment]
Note that the TF information (for displaying the robot) is internally computed from the CoM and joint positions.

**Comment by NigerChel** [comment]
In fact, I have made a python script (as an object from the whole_body_state_msgs python classes) which publishes the following:
![robot_state_msg](https://user-images.githubusercontent.com/66029337/101436003-f6cf4b00-38d2-11eb-962e-7088368c161c.png)

But when subscribing to the topic in WholeBodyState-plugin, in this case, /robot_states, rviz dies.

```
process[reemc_rviz-1]: started with pid [26584]
rviz: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:385: virtual void Ogre::Node::setOrientation(const Ogre::Quaternion&): Assertion `!q.isNaN() && "Invalid orientation supplied as parameter"' failed.
[reemc_rviz-1] process has died [pid 26584, exit code -6, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/niger/reemc_public_ws/src/reemc_tutorials/reemc_basic_tutorials/config/reemc.rviz __name:=reemc_rviz __log:=/home/niger/.ros/log/87ff79ae-38ee-11eb-a86a-00e18c1323fb/reemc_rviz-1.log].
log file: /home/niger/.ros/log/87ff79ae-38ee-11eb-a86a-00e18c1323fb/reemc_rviz-1*.log
```


I think this is due to that I supposed at the moment that the states q,v, tau are all zero, specifically, for information about the floating base (taking into account the free-flyer joint). These arguments are necessary for the python script publisher. 

What I am thinking to do, is to subscribe from gazebo simulator q, v, and tau since they depend on time, and also get information about the floating base.

**Comment by wxmerkt** [comment]
> I think this is due to that I supposed at the moment that the states q,v, tau are all zero, specifically, for information about the floating base (taking into account the free-flyer joint). These arguments are necessary for the python script publisher.

This means that your quaternion would be `0, 0, 0, 0` - which you can also see in `base_orientation` in your screenshot. Set `w` to 1 to make it a valid quaternion and the crash should no longer appear.

**Comment by NigerChel** [comment]
After subscribing the true values q, v, in the python script, WBS-plugin displays the right model.

Thanks for your feedback!

**Comment by cmastalli** [comment]
Happy to hear this. 
I will close this issue
Feel free to create other ones if this is needed
